### ISSUE TITLE
⚙️ latest release broke the site

### ISSUE THREAD

**Issue by newbeelearn** [nunocoracao/blowfish#1365] opened 2024-03-23 10:34 UTC
**Describe the bug**
Unable to render site
**To Reproduce**
update to latest release
run hugo server
you will get 
themes/blowfish/layouts/_default/list.html:23:19": execute of template failed: template: _default/list.html:23:19: executing "main" at <.File.Path>: error calling Path: runtime error: invalid memory address or nil pointer dereference
Built in 172 ms
Error: error building site: render: failed to render pages: render of "section"

themes/blowfish/layouts/_default/list.html:23:19": execute of template failed: template: _default/list.html:23:19: executing "main" – File is nil; wrap it in if or with: {{ with .File }}{{ .Path }}{{ end }}

**Expected behavior**
It should render site

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux

**Hugo & Blowfish versions**
hugo 124, blowfish v2.62.0,

**Comment by monstermuffin** [comment] 2024-03-26 13:51
I get the same thing.

```bash
ERROR render of "section" failed: "[REDACTED]/themes/blowfish/layouts/_default/list.html:23:19": execute of template failed: template: _default/list.html:23:19: executing "main" at <.File.Path>: error calling Path: runtime error: invalid memory address or nil pointer dereference
Built in 1060 ms
Error: error building site: render: failed to render pages: render of "section" failed: "[REDACTED]/themes/blowfish/layouts/_default/list.html:23:19": execute of template failed: template: _default/list.html:23:19: executing "main" – File is nil; wrap it in if or with: {{ with .File }}{{ .Path }}{{ end }}
```

**Comment by BabaRagnarok** [comment] 2024-03-26 14:45
I have the same issue

**Comment by nunocoracao** [comment] 2024-03-26 22:13
@BabaRagnarok @monstermuffin I am doing a release right now that includes a fix... (or potential fix as I never eas able to experience the issue) could you help with testing it?

**Comment by monstermuffin** [comment] 2024-03-27 11:30
> @BabaRagnarok @monstermuffin I am doing a release right now that includes a fix... (or potential fix as I never eas able to experience the issue) could you help with testing it?

I can confirm the issue is fixed for me with this release, thanks!

**Comment by BabaRagnarok** [comment] 2024-03-27 14:36
@monstermuffin @nunocoracao Yes now is working thanks

**Comment by nunocoracao** [comment] 2024-03-27 14:41
Closing the issue thanks

**Closed by nunocoracao** 2024-03-27 14:42 UTC
Labels: bug
