### ISSUE TITLE
Error: error building site: render: failed to render pages

### ISSUE THREAD

**Issue by DarkXero-dev** [nunocoracao/blowfish#1696] opened 2024-08-18 17:58 UTC
**Describe the bug**
Failing to build site with following error

```
WARN  Module "blowfish" is not compatible with this Hugo version: 0.87.0/0.131.0; run "hugo mod graph" for more information.
Start building sites … 
hugo v0.133.0-c9777473d1369f812d727a6c07dc57ad7be7bf62+extended linux/amd64 BuildDate=2024-08-17T19:57:41Z VendorInfo=gohugoio

WARN  deprecated: .Site.Author was deprecated in Hugo v0.124.0 and will be removed in a future release. Use taxonomies instead.
Total in 30193 ms
Error: error building site: render: failed to render pages: render of "page" failed: "/run/media/techxero/XeroROG/Sites/XeroHub/themes/blowfish/layouts/_default/baseof.html:8:4": execute of template failed: template: _default/single.html:8:4: executing "_default/single.html" at <partial "head.html" .>: error calling partial: partial "head.html" timed out after 30s. This is most likely due to infinite recursion. If this is just a slow template, you can try to increase the 'timeout' config setting.
```

**To Reproduce**
Just try to run server or generate site both will fail

**Expected behavior**
For it to work

**Desktop (please complete the following information):**
 - OS: ArchLinux
 - Browser Vivaldi
 - Version 68

**Hugo & Blowfish versions**
Hugo extended 0.133 / Latest Blowfish
`hugo v0.133.0-c9777473d1369f812d727a6c07dc57ad7be7bf62+extended linux/amd64 BuildDate=2024-08-17T19:57:41Z VendorInfo=gohugoio`

**Comment by ragibson** [comment] 2024-08-19 16:43
Possible duplicate of https://github.com/nunocoracao/blowfish/issues/1595, and there's a bit of a hacky workaround in that thread that may help

**Comment by nunocoracao** [comment] 2024-09-03 21:48
Closing as duplicate

**Closed by nunocoracao** 2024-09-03 21:48 UTC
