### ISSUE TITLE
Cannot built with Hugo v0.124.1

### ISSUE THREAD

**Issue by yuntan** [nunocoracao/blowfish#1367] opened 2024-03-23 22:54 UTC
**Describe the bug**
My site cannot be built with Hugo v0.124.1 due to `{{ .File }}` in HTML templates is nil.

**To Reproduce**
1. Install Hugo v0.124.1
2. `hugo`

```
hugo
Start building sites …
hugo v0.124.1-db083b05f16c945fec04f745f0ca8640560cf1ec+extended darwin/arm64 BuildDate=2024-03-20T11:40:10Z VendorInfo=brew

ERROR render of "section" failed: "/Users/yuto/Work/blog.untan.xyz/themes/blowfish/layouts/_default/list.html:20:7": execute of template failed: template: _default/list.html:20:7: executing "main" at <partial "article-meta/list.html" (dict "context" . "scope" "single")>: error calling partial: "/Users/yuto/Work/blog.untan.xyz/themes/blowfish/layouts/partials/article-meta/list.html:17:32": execute of template failed: template: partials/article-meta/list.html:17:32: executing "partials/article-meta/list.html" at <partial "meta/views.html" .>: error calling partial: "/Users/yuto/Work/blog.untan.xyz/themes/blowfish/layouts/partials/meta/views.html:7:25": execute of template failed: template: partials/meta/views.html:7:25: executing "partials/meta/views.html" at <.File.Path>: error calling Path: runtime error: invalid memory address or nil pointer dereference
Total in 288 ms
Error: error building site: render: failed to render pages: render of "section" failed: "/Users/yuto/Work/blog.untan.xyz/themes/blowfish/layouts/_default/list.html:20:7": execute of template failed: template: _default/list.html:20:7: executing "main" – File is nil; wrap it in if or with: {{ with partial "article-meta/list.html" (dict "context" . "scope" "single")>: error calling partial: "/Users/yuto/Work/blog.untan.xyz/themes/blowfish/layouts/partials/article-meta/list.html:17:32": execute of template failed: template: partials/article-meta/list.html:17:32: executing "partials/article-meta/list.html" at <partial "meta/views.html" .>: error calling partial: "/Users/yuto/Work/blog.untan.xyz/themes/blowfish/layouts/partials/meta/views.html:7:25": execute of template failed: template: partials/meta/views.html:7:25: executing "partials/meta/views.html" at <.File }}{{ .Path }}{{ end }}
```

**Expected behavior**
My site is built.

**Screenshots**
<img width="1695" alt="image" src="https://github.com/nunocoracao/blowfish/assets/574575/7f091d98-984b-4c72-a26a-7394dd4e6cfa">

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Arc
 - Version: 1.35.0

**Hugo & Blowfish versions**
Hugo: v0.124.1
Blowfish: dev (bafc42f)

**Additional context**
Replacing `{{ .File.Path }}` in `layouts/partials/meta/views.html` and `layouts/partials/meta/likes.html` with `{{ .Path }}` makes build runs.

Related: #1282 #1349

**Comment by DevOpsDownUnder** [comment] 2024-03-24 01:27
I'm getting the same error.
![image](https://github.com/nunocoracao/blowfish/assets/161704454/6f17172a-658d-4622-b322-3989869ba966)

**Comment by yuntan** [comment] 2024-03-24 01:59
@DevOpsDownUnder This error (layout/_default/list.html) is fixed by #1359 . Please try `dev` branch.

**Comment by DevOpsDownUnder** [comment] 2024-03-24 02:04
I reverted to ab87f4cbad369be22963553b516ee57bbdc38d26 and that is working for now. I'll investigate the dev branch in a couple of days when I'm working on that site again. Thank you for patch though, I appreciate the effort

**Comment by nunocoracao** [comment] 2024-03-26 22:09
Closing this issue as I can't reproduce the bug. I have two sites working with this version and the fix provided by @yuntan breaks them both. @DevOpsDownUnder merging dev into a new release now ping me if the problem persists after this.

**Closed by nunocoracao** 2024-03-26 22:09 UTC

**Comment by yuntan** [comment] 2024-03-26 22:31
Thank you for your quick response and for looking into this issue. I'll re-check my installation and configuration.
