### ISSUE TITLE
Unable to install blowfish using mod

### ISSUE THREAD

**Issue by b-palaniappan** [nunocoracao/blowfish#8] opened 2022-09-15 02:40 UTC
Go version,
```bash
❯ go version
go version go1.19.1 darwin/arm64
```
Hugo version,
```bash
❯ hugo version
hugo v0.102.3+extended darwin/arm64 BuildDate=unknown
```

When I added blowfish as module and then run `hugo server` I am getting error,
```bash
❯ hugo server
go: no module dependencies to download
go: added github.com/nunocoracao/blowfish v0.0.0-20220913200201-c81a160d88fc
hugo: collected modules in 1275 ms
WARN 2022/09/14 21:25:33 Module "github.com/nunocoracao/blowfish" is not compatible with this Hugo version; run "hugo mod graph" for more information.
Start building sites …
hugo v0.102.3+extended darwin/arm64 BuildDate=unknown
```
Error - `WARN 2022/09/14 21:25:33 Module "github.com/nunocoracao/blowfish" is not compatible with this Hugo version; run "hugo mod graph" for more information.`
and nothing is added to themes folder.

**Comment by nunocoracao** [comment] 2022-09-15 09:33
@b-palaniappan I wasn't able to reproduce the issue even with the same versions of go and Hugo you described. Could you provide more details on the steps you used to create the site and install the theme? Thanks

**Comment by nunocoracao** [comment] 2022-09-19 21:35
@b-palaniappan can you please check if the issue is resolved or provide more details? 

https://github.com/nunocoracao/blowfish/pull/16 might have helped regarding this issue... available in main [v1.1.1](https://github.com/nunocoracao/blowfish/releases/tag/v1.1.1)

**Comment by nunocoracao** [comment] 2022-09-21 22:56
@b-palaniappan any updates on this issue? Is the problem solved? If not, could you provide more details?

**Comment by nunocoracao** [comment] 2022-09-28 20:42
@b-palaniappan no updates on this issue for 15 days I am closing the ticket. Please do reopen with more details if the problem persists. Thanks

**Closed by nunocoracao** 2022-09-28 20:42 UTC
Labels: question
