### ISSUE TITLE
🐛 `getBoundingClientRect()` call on `null` error logged on pages with little content

### ISSUE THREAD

**Issue by DanWiseProgramming** [nunocoracao/blowfish#722] opened 2023-05-12 15:21 UTC
**Describe the bug**
On pages with little content where the `top-scroller` div does not get added to the DOM, the browser logs the following error, after the code changes in pull request #713 were merged:
```
Uncaught TypeError: Cannot read properties of null (reading 'getBoundingClientRect')
    at appearance.min.359cad4f07e1f431c88ecadb9ac328f981cba38d5cfb02f49375f61a0852c41d544c9261f9403f7e77432d8e12c5206d175a98a3bfe36fb80e3fa4f9417d5f85.js:1:2033
```

**To Reproduce**
1. Create page with little content (not enough for 'scroll to top' button to appear and `top-scroller` div to be added to DOM)
2. Open Console
3. See logged error

**Expected behavior**
No error should be logged in the console for pages with little content and no 'scroll to top' button.
Perhaps there should be a check whether `top-scroller` is `null` before invoking the `getBoundingClientRect()` function on it?

**Screenshots**
Error:

![Console error](https://github.com/nunocoracao/blowfish/assets/22768251/47adaba5-39dc-48b8-a732-54a77115fc6e)

Short page - `top-scroller` is not in DOM and an error is logged to console:

![Short page](https://github.com/nunocoracao/blowfish/assets/22768251/73f7847e-5190-4944-ba7c-ccbc7b520b54)

Long page - top-scroller is present and no error is logged to console:

![Long page](https://github.com/nunocoracao/blowfish/assets/22768251/6d4fc0b3-2a12-4df1-83b9-89f68016e686)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Brave
 - Version: 1.51.114 Chromium: 113.0.5672.92 (Official Build) (64-bit)

**Hugo & Blowfish versions**
- Hugo: v0.111.3-5d4eb5154e1fed125ca8e9b5a0315c4180dab192 linux/amd64
- Blowfish: 2.33.2

**Additional context**
[Relevant code](https://github.com/nunocoracao/blowfish/pull/713/files#diff-9e2de3cbae661587c6aa3678cc49a1fba9bca4aa7bae2c7150fb0127a4494fdcR72)

**Comment by nunocoracao** [comment] 2023-05-13 18:11
Thanks @DanWiseProgramming

**Comment by nunocoracao** [comment] 2023-05-23 11:48
@DanWiseProgramming was not able to reproduce
Did a fix for this in https://github.com/nunocoracao/blowfish/pull/734 
Can you test and re-open if this is not fixed?

**Closed by nunocoracao** 2023-05-23 11:48 UTC
Labels: bug

**Comment by DanWiseProgramming** [comment] 2023-05-25 22:13
@nunocoracao Thank you! Just re-tested, working as expected 👍🏻
