### ISSUE TITLE
📹 Video size rendering issue

### ISSUE THREAD

**Issue by martinvisser** [nunocoracao/blowfish#834] opened 2023-07-18 16:53 UTC
**Describe the bug**
After upgrading the theme to 2.37.0 I see some issues with rendering videos. I haven't changed anything else, just a new version of this theme. It worked fine with 2.36.1.

**Screenshots**
With version 2.36.1:
![236](https://github.com/nunocoracao/blowfish/assets/3170236/0cef28b8-ca31-47e7-92b9-714ad7e2be47)

With 2.37.0:
![237](https://github.com/nunocoracao/blowfish/assets/3170236/24ff7cdb-b9e1-4c3d-b948-ca2d1ece5070)

**Hugo & Blowfish versions**
Which version of Hugo and Blowfish are you using?
Hugo: v0.115.3
Blowfish: 2.37.0

**Comment by nunocoracao** [comment] 2023-07-20 20:25
Will need time to investigate this one @martinvisser could you provide access to the code? or at least which layout is this referring to?
Also, is this something you can clearly go back and forth in the versions and see the difference? or might it be caused by a change in the youtube embed for example?

**Comment by martinvisser** [comment] 2023-07-21 07:02
@nunocoracao thanks for looking into it!
When I switched back to `v2.36.1` the rendering issue was gone, so the only change I did was updating to the latest theme and back again to fix it.

The file is using the following code:
```md
---
title: "Simon's Cat in 'Cat &amp; Mouse'"
date: "2011-09-03T12:37:36"
---

{{< youtube BWIPZvwcnX8 >}}
```

And the following params:
```yaml
colorScheme: slate
defaultAppearance: dark
defaultBackgroundImage: img/background.jpg
autoSwitchAppearance: true
enableSearch: true
enableCodeCopy: true
mainSections:
  - posts
footer:
  showCopyright: true
  showThemeAttribution: true
  showAppearanceSwitcher: true
  showScrollToTop: false
header:
  layout: fixed
homepage:
  layout: background
  homepageImage: img/background.jpg
  showRecent: true
  showRecentItems: 6
  showMoreLink: true
  showMoreLinkDest: posts
  cardView: true
  cardViewScreenWidth: false
  layoutBackgroundBlur: true
article:
  showDate: true
  showViews: false
  showLikes: false
  showDateUpdated: false
  showAuthor: false
  showHero: true
  heroStyle: background
  layoutBackgroundHeaderSpace: false
  layoutBackgroundBlur: true
  showBreadcrumbs: false
  showDraftLabel: true
  showEdit: false
  editAppendPath: true
  showHeadingAnchors: true
  showPagination: true
  invertPagination: true
  showReadingTime: true
  showTableOfContents: false
  showTaxonomies: false
  showAuthorsBadges: false
  showWordCount: false
  showSummary: true
  sharingLinks:
    - linkedin
    - pinterest
    - reddit
    - facebook
    - email
list:
  showHero: true
  heroStyle: background
  layoutBackgroundHeaderSpace: false
  layoutBackgroundBlur: true
  showBreadcrumbs: false
  showSummary: true
  showTableOfContents: false
  showCards: true
  groupByYear: false
  cardView: true
  cardViewScreenWidth: false
sitemap:
  excludedKinds:
    - taxonomy
    - term
taxonomy:
  showTermCount: true
fathomAnalytics: { }
verification: { }
imaging:
  anchor: Smart
  bgColor: '#1f2937'
  hint: photo
  quality: 75
  resampleFilter: box
galleryLoadJQuery: true
gallerySortOrder: asc
galleryRowHeight: 150
galleryMargins: 5
galleryThumbnailResizeOptions: "600x450 webp photo"
galleryImageResizeOptions: "1440x1080 webp photo"
galleryShowExif: false
galleryPreviewType: blur
galleryEmbedPreview: false
galleryThumbnailHoverEffect: enlarge
galleryLastRow: nojustify
```

If you need more, please let me know!

**Comment by nunocoracao** [comment] 2023-07-21 07:03
Is this the landing page? A list? An article?

**Comment by martinvisser** [comment] 2023-07-21 07:05
It's an article

**Comment by nunocoracao** [comment] 2023-07-21 07:11
Awesome I think I know where the problem might be...

**Comment by nunocoracao** [comment] 2023-07-29 12:38
fixed in https://github.com/nunocoracao/blowfish/pull/851

**Closed by nunocoracao** 2023-07-29 12:38 UTC

**Comment by martinvisser** [comment] 2023-07-29 15:02
It does now indeed render differently, but also not the same as before. Before it took the whole width, now it's about 2/3 the width of the container:
![image](https://github.com/nunocoracao/blowfish/assets/3170236/087476d7-e42b-41cd-9cae-de99b93145be)

**Comment by nunocoracao** [comment] 2023-07-29 16:36
This is the intended behavior, mas width of that section is suppose to be the prose class in tailwind. You can always embed html in your markdown to take over the full width.

**Comment by nunocoracao** [comment] 2023-07-29 18:37
@martinvisser headsup
Might need to revert this change, it introduced a bug in mobile. Will check if I can fix that bug without full reverting what you requested for.

**Comment by nunocoracao** [comment] 2023-07-29 21:23
Hello again @martinvisser I was not able to solve the bug without reverting to the same problem you are finding. 
However, I think I have a solution. I also have a one page video in my personal page and I was able to make it work:

Here's the example:
https://nunocoracao.com/posts/202211-static-feedback/

and the code
https://github.com/nunocoracao/nunocoracao.com/blob/main/content/posts/202211-static-feedback/index.md

Not sure what is going on in your example but I would have a look.

**Comment by martinvisser** [comment] 2023-07-29 21:25
Thanks for the heads-up. I'll check it out and report back.

**Comment by martinvisser** [comment] 2023-07-30 12:10
As I don't have any text the content seems to rendered as wide as the sharing links in my case. If I put enough text on the page it renders full width, but I just don't have any text. It's just the embedded video.

I see a [commit](https://github.com/nunocoracao/blowfish/commit/ada2b2c99bb953e497ea4c71f83f35e91617ebab) that changed `<div class="min-w-0 min-h-0 max-w-prose">` to `<div class="min-w-0 min-h-0 max-w-fit">`. I'm no expert, but when I put that back it renders as full width again and seems to be properly responsive. But I guess you changed that for an issue around TOC. However, as I don't show a TOC (`showTableOfContents = false`) it would nice if it was able to render in both situations. For now I just copied the `single.html` and reverted back to use `max-w-prose` as that seems to work for me.

**Comment by nunocoracao** [comment] 2023-07-30 13:54
I would play around with html within the md file. Or a custom iframe to embed the youtube video.
