### ISSUE TITLE
🐛 Chromium: on page load "settling shift"

### ISSUE THREAD

**Issue by rpstreef** [nunocoracao/blowfish#697] opened 2023-05-01 07:46 UTC
**Describe the bug**
On page load the entire design moves slightly to the right and settles back again.

With mobile browser versions of Chrome this does not seem to happen.
On Firefox this does not happen, mobile or desktop.

**To Reproduce**
1. Go to https://www.vitalityviewpoint.com/time-frames/
2. Click on any of the top level menu items and you'll see the shift

**Expected behavior**
No shifting of the page

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Chromium (Chrome) 
 - Version 112.0.5615.165

**Hugo & Blowfish versions**
Hugo:  v0.111.3+extended linux/amd64 BuildDate=unknown
Blowfish: v2.32.1

**Additional information**
I believe it may have something to do with the list/taxonomy `cardView`, when I set it to disabled a lot of the shifting seems to go away.
Perhaps the image resizing could affect it?

**Comment by nunocoracao** [comment] 2023-05-01 09:33
Thanks for the feedback @rpstreef. I was not able to reproduce it. The link you shared doesn't open and I don't see that behavior in any of the sites I manage using Blowfish. Could you double-check after updating to the latest version and update the ticket?

**Comment by rpstreef** [comment] 2023-05-02 03:30
Please review this git repo:

https://github.com/rpstreef/hugo-blowfish-test

I've reproduced the problem

**Comment by nunocoracao** [comment] 2023-05-04 21:01
Still no luck, @rpstreef can I ask you for a video so that I 👀  what you 👀 ?

**Comment by rpstreef** [comment] 2023-05-05 01:45
Did you click through all the navigation menus at the top on Chrome desktop browser?

**Comment by nunocoracao** [comment] 2023-05-07 14:40
Saw it in the video, is [this](https://github.com/rpstreef/hugo-blowfish-test) the repo for that video? 
I'll have a look. Feels like it might be related with the contents of the pages or configs, that doesn't happen in any of my pages. 

(note: I have little time at the moment so this might take a while to fix, sorry for that @rpstreef )

**Comment by rpstreef** [comment] 2023-05-07 15:57
As stated, the repo reproduces this and the other issue where referenced. 
I'm fairly confident it has something to do with the card image, either size or the way its resized.

**Comment by nunocoracao** [comment] 2023-05-08 20:45
I pulled the repo again, try it out. No luck - here is a video with no shift happening. Closing this one
https://user-images.githubusercontent.com/3803196/236931077-e3c9f056-cc21-4921-b20e-d8fb1c6edb27.mov

**Closed by nunocoracao** 2023-05-08 20:45 UTC
Labels: not reproducible, waiting info

**Comment by rpstreef** [comment] 2023-05-09 05:19
Apparently this seems to be Chromium specific and not Chrome browser?
I'm failing to understand why this is happening on my version and not on yours

**Comment by rpstreef** [comment] 2023-05-10 08:15
to make sure, Ive loaded up Windows 11 with both Edge browser and Chrome I get this page shifting to happen.

It's rather premature to close this ticket, perhaps it make more sense to clarify under which conditions you have run the provided github repo and go from there
