### ISSUE TITLE
Multiple authors appears in a page but not in a post

### ISSUE THREAD

**Issue by freerbeing** [nunocoracao/blowfish#797] opened 2023-07-05 14:39 UTC
Apologies for additional issues ... 

I have implemented multiple authors as specified
The author appears as it should on a page, but not in a post.

A template file, I assume
But which?

Here is my repo:
https://github.com/freerbeing/peoplespoetry

Netlify deploy:
https://startling-bunny-d5adab.netlify.app/

**Comment by nunocoracao** [comment] 2023-07-05 21:07
Hello @freerbeing not a bug probably a problem with the configs. Feel free to open a topic in discussions. Closing this as this is not an issue. Also you can check my personal site as I use that feature for the post titled "Apes and Kittens in the Music Industry" - https://github.com/nunocoracao/nunocoracao.com

**Closed by nunocoracao** 2023-07-05 21:07 UTC
