### ISSUE TITLE
Chrome (chome based browser) shift

### ISSUE THREAD

**Issue by rpstreef** [nunocoracao/blowfish#746] opened 2023-05-27 09:27 UTC
Describe the bug
On page load the entire design moves slightly to the right and settles back again.

With mobile browser versions of Chrome this does not seem to happen.
On Firefox this does not happen, mobile or desktop.

To Reproduce

    Open on Edge, Chrome or Chromium
    Git pull https://github.com/rpstreef/hugo-blowfish-test
    Click on any of the top level menu items and you'll see the shift

Expected behavior
No shifting of the page

Desktop (please complete the following information):

    OS: Linux
    Browser Chromium (Chrome)
    Version 112.0.5615.165

Hugo & Blowfish versions
Hugo: v0.111.3+extended linux/amd64 BuildDate=unknown
Blowfish: v2.32.1

Additional information
I believe it may have something to do with the list/taxonomy cardView, when I set it to disabled a lot of the shifting seems to go away.
Perhaps the image resizing could affect it?

Since this has not been resolved and just closed, I've reopened this

**Comment by nunocoracao** [comment] 2023-05-31 22:25
duplicate https://github.com/nunocoracao/blowfish/issues/697

**Comment by nunocoracao** [comment] 2023-05-31 22:26
Thanks @rpstreef I tried (again) to follow the steps and didn't see any shift with the latest version of the theme. 
I am using Max as an OS and tested using Chrome. 
Closing ticket again

**Closed by nunocoracao** 2023-05-31 22:26 UTC

**Comment by rpstreef** [comment] 2023-06-01 04:09
@nunocoracao 
I have a video that proves it, I gave you the git repo based off the video.
Again, you close the ticket.

It's obvious the problem isn't solved. I'm not sure why you keep closing these tickets. Anyway, I wont bother providing any issue reports any longer because this is a waste of time it seems

**Comment by nunocoracao** [comment] 2023-06-01 06:37
@rpstreef you opened a duplicated ticket without any new information expecting a different outcome. I still tried reproducing the problem to no success with the latest update. No one else complained or interacted with then any of the tickets. I would suggest open a discussion to see if more people have this problem and if it's caused by a bug or something else.

**Comment by rpstreef** [comment] 2023-06-01 06:53
I reopened it, because you closed it without proper consideration for other experiences except your own.
We are but two people, 50 percent has experienced the bug and has provided the evidence.
To now reply and point the finger, it's not very productive.
You either use bug report tickets to gather this information, OR you point to a discussion or other means of collecting information instead of just shutting it down.

**Comment by crodrigocs** [comment] 2023-06-01 14:38
@rpstreef I noticed the shifting when looking at https://www.vitalityviewpoint.com/health-goals. However, the shifting IS NOT a theme problem. What causes the shifting is the vertical scrollbar the browser adds to the right when displaying longer content. Check it again and you will see what I'm talking about. There's nothing really that can be done.
